### ISSUE TITLE
No margin-left for H1 element of webpage

### ISSUE THREAD

**Issue by harshitagrawal294** [Bluegrunge/Bluegrunge.github.io#1]
**Describe the bug**
Their is no space bewteen left boundary and the header of webpage 
"Providing creative 
solutions to turn your 
ideas into reality"
in Desktop view(>600px width)

**To Reproduce**
1. Go to "https://bluegrunge.github.io/" on chrome in Desktop site.

**Expected behavior**
 There should be some space between heading and left boundary.

**Screenshots**
![Screenshot from 2019-07-15 17-15-00](https://user-images.githubusercontent.com/44468673/61214103-9f03d300-a724-11e9-8081-cc02147957a9.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 10.04
 - Browser : chrome
 - Version : Chrome 75 on Linux

**Smartphone (please complete the following information):**
 - Problem doesn't exist

**Additional context**

**Comment by Bluegrunge** [comment]
@harshitagrawal294 
Hey.
Thanks for your contribution.
The problem seems to persist even now. I would recommend you to host this website on a free account on github/000webhost.
Please fix the problem and make a new PR.

**Comment by Bluegrunge** [comment]
@harshitagrawal294 Thanks for solving the issue.
